<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>2_Promise实例的then方法理解</title>
</head>

<body>
    <script>
        let p1 = new Promise(function (resolve, reject) {// 执行器函数
            // 执行器函数中影响p1状态和结果的行为：
            // 1.执行resolve时，p1为成功状态，结果为参数
            // 2.执行reject时，p1为失败状态，结果为参数
            // 3.出现异常行为，p1为失败状态，结果为错误信息/抛出的值
            // resolve(123)
            reject(456)
        })

        /*
        then 方法用于指定 Promise 对象成功状态和失败状态的回调函数
        then 方法执行后返回一个新的 Promise 对象（链式调用 p1.then().then().then()）

        执行器函数内部可以改变 p1 的状态和结果
        */
        p1.then(function (res) {// 异步执行 成功的回调
            console.log('p1 成功', res);
            // 可以改变 p2 的状态的行为有：
            // 1.return 返回 非Promise 值时,p2 为成功状态，结果为返回的值
            // return undefined;// 默认
            // return 123;
            // return [1,2,3];

            // 2.return 返回 Promise 值时,p2 的状态和结果跟随返回的 Promise对象
            return new Promise((resolve, reject) => {
                // resolve(33);
                reject(44);
            });

            // 3.出现异常行为时,p2 为失败状态,结果为错误信息/抛出的值
            // throw 'error';
            // throw new Error('出错啦');

        }, function (err) { // 异步执行 失败的回调
            console.log('p1 失败', err);
            // 可以改变 p2 的状态的行为有：
            // 1.return 返回 非Promise 值时,p2 为成功状态，结果为返回的值
            // return undefined;// 默认
            // return 123;
            // return [1,2,3];

            // 2.return 返回 Promise 值时,p2 的状态和结果跟随返回的 Promise对象
            return new Promise((resolve, reject) => {
                // resolve(33);
                reject(44);
            });

            // 3.出现异常行为时,p2 为失败状态,结果为错误信息/抛出的值
            // throw 'error';
            // throw new Error('出错啦');
        })// p2 的状态和结果取决于 p1 回调函数的返回值
        .then(function (res) {
            console.log('p2 成功', res);
        }, function (err) {
            console.log('p2 失败', err);
        })





    </script>
</body>

</html>